name: ci

on:
  push:
    branches:
      - develop
      - releases/**
  pull_request:
    branches:
      - develop
      - releases/**

jobs:
  windows:
    uses: ./.github/workflows/windows_python.yml
