name: linux tests

on:
  push:
    branches:
      - develop
      - releases/**
  pull_request:
    branches:
      - develop
      - releases/**
jobs:
  # Test for Python2.6 run on Centos 6
  centos6:
    runs-on: ubuntu-latest
    container: spack/github-actions:centos6
    steps:
    - name: Run unit tests (full test-suite)
      # The CentOS 6 container doesn't run with coverage, but
      # under the same conditions it runs the full test suite
      env:
          HOME: /home/spack-test
          SPACK_TEST_SOLVER: original
      run: |
          whoami && echo $HOME && cd $HOME
          git clone "${{ github.server_url }}/${{ github.repository }}.git" && cd spack
          git fetch origin "${{ github.ref }}:test-branch"
          git checkout test-branch
          . .github/workflows/setup_git.sh
          bin/spack unit-test -x
