name: unit tests

on:
  pull_request:
    branches:
      - develop

jobs:
  windows:
    defaults:
      run:
        shell:
          powershell Invoke-Expression -Command "./share/spack/qa/windows_test_setup.ps1"; {0}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 0
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: 3.9
    - name: Install Python packages
      run: |
          python -m pip install --upgrade pip pywin32 setuptools pytest-cov clingo
    - name: Create local develop
      run: |
        ./.github/workflows/bin/setup_git.ps1
    - name: Unit Test
      env:
        COVERAGE_FILE: coverage/.coverage-windows
      run: |
        spack unit-test -x --verbose --cov --cov-config=pyproject.toml -k grep
        ./share/spack/qa/validate_last_exit.ps1
    - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
      with:
        name: coverage-windows
        path: coverage
        include-hidden-files: true
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
