name: windows

on: [push, pull_request]

defaults:
  run:
    shell:
     powershell Invoke-Expression -Command "./share/spack/qa/windows_test_setup.ps1"; {0}

jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        fetch-depth: 0
    - uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b
      with:
        python-version: 3.9
    - name: Install Python packages
      run: |
          python -m pip install --upgrade pip pywin32 setuptools pytest-cov clingo
    - name: Create local develop
      run: |
        ./.github/workflows/setup_git.ps1
    - name: Unit Test
      run: |
        spack unit-test -x --verbose --cov --cov-config=pyproject.toml --ignore=lib/spack/spack/test/cmd lib/spack/spack/test/installer.py -k test_overwrite_install_does_install_build_deps
        ./share/spack/qa/validate_last_exit.ps1
        coverage combine -a
        coverage xml
    - uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2
      with:
        flags: unittests,windows
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
